#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- $fullName := include "common.fullname" . }}
{{- $hostMountPath := include "common.baseHostPath" "" }}
{{- $_ := mergeOverwrite .Values.csi (index .Values "alluxio-csi") }}

{{- if .Values.csi.enabled }}

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}-csi-nodeplugin
  labels:
    {{- include "common.labels" (dict "component" "csi-nodeplugin" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.matchLabels" (dict "component" "csi-nodeplugin" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" (dict "component" "csi-nodeplugin" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      serviceAccountName: alluxio-csi-sa
      hostNetwork: {{ .Values.csi.hostNetwork }}
      dnsPolicy: {{ .Values.csi.dnsPolicy | default (.Values.csi.hostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
      {{- include "alluxio-operator.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.csi.nodePlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.csi.nodePlugin.nodeSelector | trim | nindent 8 }}
      {{- end }}
      {{- if .Values.csi.nodePlugin.affinity }}
      affinity:
        {{- toYaml .Values.csi.nodePlugin.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.csi.nodePlugin.tolerations }}
      tolerations:
        {{- toYaml .Values.csi.nodePlugin.tolerations | trim | nindent 8 }}
      {{- end }}
      containers:
        - name: csi-nodeserver
          {{- if .Values.csi.nodePlugin.nodeserver.resources }}
          resources:
            {{- toYaml .Values.csi.nodePlugin.nodeserver.resources | trim | nindent 12 }}
          {{- end }}
          image: {{ include "alluxio-operator.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/usr/local/bin/alluxio-csi"]
          args :
            - node
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--metric={{ .Values.csi.nodePlugin.nodeserver.ports.metric }}"
            {{- if .Values.csi.nodePlugin.nodeserver.debugLog }}
            - "--debug-log"
            {{- end }}
            {{- if .Values.csi.useFixedStagingPath }}
            - "--fixed-staging"
            {{- end }}
          env:
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          securityContext:
            privileged: true # required by bidirectional mount
            runAsUser: 0 # required by CSI
            runAsGroup: 0 # required by CSI
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            {{- if .Values.csi.useFixedStagingPath }}
            - name: alluxio-fuse-mount
              mountPath: {{ $hostMountPath }}
              mountPropagation: "HostToContainer"
            {{- end }}
            - name: pods-mount-dir
              mountPath: {{ .Values.csi.kubeletPath }}
              mountPropagation: "Bidirectional"
            {{- if .Values.useLocaltime }}
            - name: system-localtime
              mountPath: /etc/localtime
            {{- end }}
        - name: node-driver-registrar
          image: {{ $.Values.global.azure.images.registrar.registry }}/{{ $.Values.global.azure.images.registrar.image }}:{{ $.Values.global.azure.images.registrar.tag }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/alluxio /registration/alluxio-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path={{ .Values.csi.kubeletPath }}/plugins/csi-alluxio-plugin/csi.sock
          {{- if .Values.csi.nodePlugin.driverRegistrar.resources }}
          resources:
            {{- toYaml .Values.csi.nodePlugin.driverRegistrar.resources | trim | nindent 12 }}
          {{- end }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: plugin-dir
          hostPath:
            path: {{ .Values.csi.kubeletPath }}/plugins/csi-alluxio-plugin
            type: DirectoryOrCreate
        {{- if .Values.csi.useFixedStagingPath }}
        - name: alluxio-fuse-mount
          hostPath:
            path: {{ $hostMountPath }}
            type: DirectoryOrCreate
        {{- end }}
        - name: pods-mount-dir
          hostPath:
            path: {{ .Values.csi.kubeletPath }}
            type: Directory
        - name: registration-dir
          hostPath:
            path: {{ .Values.csi.kubeletPath }}/plugins_registry
            type: Directory
        {{- if .Values.useLocaltime }}
        - name: system-localtime
          hostPath:
            path: /etc/localtime
            type: File
        {{- end }}

{{- end }}
