# =======================================================================
# Global image
# =======================================================================
global:
  azure:
    images:
      operator:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      csi-provisioner:
        tag: v2.0.5
        image: csi-provisioner
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/csi-provisioner:v2.0.5
      node-driver-registrar:
        tag: v2.0.0
        image: csi-node-driver-registrar
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/csi-node-driver-registrar:v2.0.0
      csi-nodeserver:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      doctor-controller:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      cluster-controller:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      ufs-controller:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      license-controller:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      console:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      csi-controller:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      foundationdb-kubernetes-init:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5
      manifest:
        tag: 3.4.5
        image: k8s-operator
        registry: alluxio.azurecr.cn/alluxio
        full: alluxio.azurecr.cn/alluxio/k8s-operator:3.4.5

# ========================================================================
# Alluxio Operator Configuration (Sub-Chart Pass-through)
# ========================================================================
alluxio-operator:
  enabled: true
  # 在这里覆盖子 Chart alluxio-operator 的 values
  # 例如：
  image: alluxio.azurecr.cn/alluxio/k8s-operator
  imageTag: 3.4.5
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  
  console:
    web:
      authType: none
  
  clusterController:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 64Mi
  
  ufsController:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
  
  collectinfoController:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
  
  csi:
    enabled: true
    fullnameOverride: alluxio
  
    controllerPlugin:
      provisioner:
        image: alluxio.azurecr.cn/alluxio/csi-provisioner:v2.0.5
  
    nodePlugin:
      driverRegistrar:
        image: alluxio.azurecr.cn/alluxio/csi-node-driver-registrar:v2.0.0
