#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- if .Values.console.enabled }}
{{- $fullName := include "common.fullname" . }}
{{- $operatorConsoleLogDir := include "common.basePath" "/logs" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-console
  labels:
    {{- include "common.labels" (dict "component" "console" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
data:
  operator-console.yaml: |
    server:
      port: {{ .Values.console.service.ports.api }}
    log:
      level: {{ .Values.console.log.level }}
      path: {{ $operatorConsoleLogDir }}/operator-console.log

    web:
      authType: {{ .Values.console.web.authType }}
      issuerURL: {{ include "alluxio-operator.console.issuerURL" . }}
      clientID: {{ include "alluxio-operator.console.clientID" . }}
{{- end }} 
